### ISSUE TITLE
Lab 4. Recursion

### ISSUE THREAD

**Issue by jhnh198** [jhnh198/CS304#1]
Need to make the Lab find 20 paths for the recursion algorithm. May want to used an algorithm(math equation) rather than an open recursive solution

**Comment by jhnh198** [comment]
CS304/CS304DataStructures/src/Week5/LabFourRecursion.java

**Comment by jhnh198** [comment]
Off by one

**Comment by nkup32** [comment]
Hey John, I went to the doctors office today. I had some blood where it
shouldn't be. I'll work on it.

Nick

**Comment by jhnh198** [comment]
I'm sorry to hear that. I figured it out. If you need help, let me know.

**Comment by nkup32** [comment]
Hey John, could you let professor T know I can't make it again? I have to
go to my doctors office again today. Tell him I apologize profusely.

Nick
